// This JLex file was machine-generated by the BNF converter
package fafl;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  public int line_num() { return (yyline+1); }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		93,
		95,
		95,
		95,
		97,
		99
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NO_ANCHOR,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NOT_ACCEPT,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NOT_ACCEPT,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NOT_ACCEPT,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NOT_ACCEPT,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NOT_ACCEPT,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NOT_ACCEPT,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NOT_ACCEPT,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NOT_ACCEPT,
		/* 84 */ YY_NO_ANCHOR,
		/* 85 */ YY_NOT_ACCEPT,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NOT_ACCEPT,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NOT_ACCEPT,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NOT_ACCEPT,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NOT_ACCEPT,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NOT_ACCEPT,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NOT_ACCEPT,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NOT_ACCEPT,
		/* 100 */ YY_NO_ANCHOR,
		/* 101 */ YY_NO_ANCHOR,
		/* 102 */ YY_NO_ANCHOR,
		/* 103 */ YY_NO_ANCHOR,
		/* 104 */ YY_NO_ANCHOR,
		/* 105 */ YY_NO_ANCHOR,
		/* 106 */ YY_NO_ANCHOR,
		/* 107 */ YY_NO_ANCHOR,
		/* 108 */ YY_NO_ANCHOR,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NO_ANCHOR,
		/* 111 */ YY_NO_ANCHOR,
		/* 112 */ YY_NO_ANCHOR,
		/* 113 */ YY_NO_ANCHOR,
		/* 114 */ YY_NO_ANCHOR,
		/* 115 */ YY_NO_ANCHOR,
		/* 116 */ YY_NO_ANCHOR,
		/* 117 */ YY_NO_ANCHOR,
		/* 118 */ YY_NO_ANCHOR,
		/* 119 */ YY_NO_ANCHOR,
		/* 120 */ YY_NO_ANCHOR,
		/* 121 */ YY_NO_ANCHOR,
		/* 122 */ YY_NO_ANCHOR,
		/* 123 */ YY_NO_ANCHOR,
		/* 124 */ YY_NO_ANCHOR,
		/* 125 */ YY_NO_ANCHOR,
		/* 126 */ YY_NO_ANCHOR,
		/* 127 */ YY_NO_ANCHOR,
		/* 128 */ YY_NO_ANCHOR,
		/* 129 */ YY_NO_ANCHOR,
		/* 130 */ YY_NO_ANCHOR,
		/* 131 */ YY_NO_ANCHOR,
		/* 132 */ YY_NO_ANCHOR,
		/* 133 */ YY_NO_ANCHOR,
		/* 134 */ YY_NO_ANCHOR,
		/* 135 */ YY_NO_ANCHOR,
		/* 136 */ YY_NO_ANCHOR,
		/* 137 */ YY_NO_ANCHOR,
		/* 138 */ YY_NO_ANCHOR,
		/* 139 */ YY_NO_ANCHOR,
		/* 140 */ YY_NO_ANCHOR,
		/* 141 */ YY_NO_ANCHOR,
		/* 142 */ YY_NO_ANCHOR,
		/* 143 */ YY_NO_ANCHOR,
		/* 144 */ YY_NO_ANCHOR,
		/* 145 */ YY_NO_ANCHOR,
		/* 146 */ YY_NO_ANCHOR,
		/* 147 */ YY_NO_ANCHOR,
		/* 148 */ YY_NO_ANCHOR,
		/* 149 */ YY_NO_ANCHOR,
		/* 150 */ YY_NO_ANCHOR,
		/* 151 */ YY_NO_ANCHOR,
		/* 152 */ YY_NO_ANCHOR,
		/* 153 */ YY_NO_ANCHOR,
		/* 154 */ YY_NO_ANCHOR,
		/* 155 */ YY_NO_ANCHOR,
		/* 156 */ YY_NO_ANCHOR,
		/* 157 */ YY_NO_ANCHOR,
		/* 158 */ YY_NO_ANCHOR,
		/* 159 */ YY_NO_ANCHOR,
		/* 160 */ YY_NO_ANCHOR,
		/* 161 */ YY_NO_ANCHOR,
		/* 162 */ YY_NO_ANCHOR,
		/* 163 */ YY_NO_ANCHOR,
		/* 164 */ YY_NO_ANCHOR,
		/* 165 */ YY_NO_ANCHOR,
		/* 166 */ YY_NO_ANCHOR,
		/* 167 */ YY_NO_ANCHOR,
		/* 168 */ YY_NO_ANCHOR,
		/* 169 */ YY_NO_ANCHOR,
		/* 170 */ YY_NO_ANCHOR,
		/* 171 */ YY_NO_ANCHOR,
		/* 172 */ YY_NO_ANCHOR,
		/* 173 */ YY_NO_ANCHOR,
		/* 174 */ YY_NO_ANCHOR,
		/* 175 */ YY_NO_ANCHOR,
		/* 176 */ YY_NO_ANCHOR,
		/* 177 */ YY_NO_ANCHOR,
		/* 178 */ YY_NO_ANCHOR,
		/* 179 */ YY_NO_ANCHOR,
		/* 180 */ YY_NO_ANCHOR,
		/* 181 */ YY_NO_ANCHOR,
		/* 182 */ YY_NO_ANCHOR,
		/* 183 */ YY_NO_ANCHOR,
		/* 184 */ YY_NO_ANCHOR,
		/* 185 */ YY_NO_ANCHOR,
		/* 186 */ YY_NO_ANCHOR,
		/* 187 */ YY_NO_ANCHOR,
		/* 188 */ YY_NO_ANCHOR,
		/* 189 */ YY_NO_ANCHOR,
		/* 190 */ YY_NO_ANCHOR,
		/* 191 */ YY_NO_ANCHOR,
		/* 192 */ YY_NO_ANCHOR,
		/* 193 */ YY_NO_ANCHOR,
		/* 194 */ YY_NO_ANCHOR,
		/* 195 */ YY_NO_ANCHOR,
		/* 196 */ YY_NO_ANCHOR,
		/* 197 */ YY_NO_ANCHOR,
		/* 198 */ YY_NO_ANCHOR,
		/* 199 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"45:9,52,43,45,52,42,45:18,52,45,46,45:4,51,3,4,44,45,9,5,10,41,48:10,2,1,11" +
",45,6,45:2,49,23,49,26,29,49:3,33,49:9,34,49:7,18,47,19,45,51,45,20,28,14,1" +
"2,17,37,35,36,13,50:2,25,40,32,24,31,39,21,16,15,27,38,50,30,22,50,7,45,8,4" +
"5:66,49:23,45,49:7,50:24,45,50:8,45:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,200,
"0,1:11,2,1:4,3,1,4:2,1,4:6,1,5,6,4:19,1,4:2,1,4:2,1:11,7,8,9,10,11,12,13,14" +
",15,16,17,4,18,19,9,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,3" +
"8,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,6" +
"3,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,8" +
"8,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109," +
"110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,4,127,1" +
"28,129,130,131,132,133,134,135,136")[0];

	private int yy_nxt[][] = unpackFromString(137,53,
"1,2,3,4,5,67,6,7,8,9,10,11,12,68,157,174,181,185,13,14,187,188,189,190,72,1" +
"91,192,189:2,193,189,194,189,195,196,197,189,198,189:2,199,71,15:2,-1:2,16," +
"-1,17,189:2,-1,15,-1:65,189,74,189:3,76,-1:2,189:3,78,189:2,78,189:2,78,189" +
":3,78:2,189:6,-1:7,78:2,189,78,-1:11,75,-1:37,17,-1:16,189:6,-1:2,189:3,78," +
"189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:18,77,-1:30,29,-1:9," +
"79,-1:6,189:6,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,18" +
"9,78,-1:7,18,-1:58,189:4,80,189,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2," +
"189:2,19,189:3,-1:7,78:2,189,78,-1:49,69,-1:45,58,-1:52,73,-1:2,21,-1:20,18" +
"9:6,-1:2,189,20,189,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78," +
"-1:2,73:42,28,73:9,-1:12,189:2,108,189:3,-1:2,189:3,78,189:2,78,189:2,78,18" +
"9:3,78:2,189:3,22,189:2,-1:7,78:2,189,78,-1:49,29,-1:16,189:6,-1:2,189:3,78" +
",189:2,78,189:2,78,189:3,78:2,189:2,178,189:3,-1:7,78:2,189,78,-1:6,81,-1:4" +
"2,69,-1:20,83,-1:48,189:6,-1:2,189:3,78,189,159,78,189:2,78,189:3,78:2,186," +
"189:5,-1:7,78:2,189,78,-1:13,189:3,165,189:2,-1:2,189:3,78,189:2,78,189:2,7" +
"8,189:3,78:2,189:6,-1:7,78:2,189,78,-1:18,87,-1:47,189:6,-1:2,189:2,23,78,1" +
"89:2,78,109,189,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:17,89,-1:48,189:5,1" +
"10,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:16," +
"50,-1:49,189:6,-1:2,189,183,189,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7," +
"78:2,189,78,-1:18,91,-1:47,189:4,112,189,-1:2,189:3,78,189:2,78,189:2,78,18" +
"9:3,78:2,189:6,-1:7,78:2,189,78,-1:16,53,-1:49,189:6,-1:2,189:3,78,189:2,78" +
",162,189,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1,1,56:41,-1,57,70,56:8,-1:1" +
"2,24,189:5,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,7" +
"8,-1,1,-1:64,189:6,-1:2,113,189:2,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:" +
"7,78:2,189,78,-1,1,59:41,-1:2,59:2,60,61,59:5,-1:12,189,114,189:4,-1:2,189:" +
"3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1,1,62:14,63,62:1" +
"6,64,62:9,-1:2,62:2,65,66,62:5,-1:12,189:6,-1:2,189:3,78,115,189,78,189:2,7" +
"8,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189:2,78,189:" +
"2,78,189:2,116,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189:2," +
"78,189:2,78,189:3,78:2,189:5,117,-1:7,78:2,189,78,-1:13,189:2,118,189:3,-1:" +
"2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:3," +
"25,189:2,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78," +
"-1:13,189:3,26,189:2,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7," +
"78:2,189,78,-1:13,189:6,-1:2,189:3,78,189,179,78,189:2,78,189:3,78:2,189:6," +
"-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189,27,78,189:2,78,189:3,78:2,18" +
"9:6,-1:7,78:2,189,78,-1:13,189:3,30,189:2,-1:2,189:3,78,189:2,78,189:2,78,1" +
"89:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:5,31,-1:2,189:3,78,189:2,78,189:" +
"2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189:2,78,1" +
"89:2,78,189:2,32,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189:" +
"2,78,189:2,78,189:3,78:2,189:4,33,189,-1:7,78:2,189,78,-1:13,189:5,34,-1:2," +
"189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,170,189:" +
"5,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,1" +
"89:4,127,189,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189" +
",78,-1:13,189:6,-1:2,189:3,78,189,35,78,189:2,78,189:3,78:2,189:6,-1:7,78:2" +
",189,78,-1:13,189:6,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,128,189:5,-1" +
":7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189:2,78,189,129,78,189:3,78:2,189" +
":6,-1:7,78:2,189,78,-1:13,189:5,130,-1:2,189:3,78,189:2,78,189:2,78,189:3,7" +
"8:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189:2,78,189:2,78,189:" +
"2,171,78:2,189:6,-1:7,78:2,189,78,-1:13,189:4,36,189,-1:2,189:3,78,189:2,78" +
",189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189,131,189:4,-1:2,189:3," +
"78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189" +
":3,78,189:2,78,134,189,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:" +
"2,189:3,78,189:2,78,189:2,78,189:3,78:2,189,37,189:4,-1:7,78:2,189,78,-1:13" +
",189:2,138,189:3,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2" +
",189,78,-1:13,189:6,-1:2,189:3,78,189,139,78,189:2,78,189:3,78:2,189:6,-1:7" +
",78:2,189,78,-1:13,189:6,-1:2,189:2,140,78,189:2,78,189:2,78,189:3,78:2,189" +
":6,-1:7,78:2,189,78,-1:13,189:5,38,-1:2,189:3,78,189:2,78,189:2,78,189:3,78" +
":2,189:6,-1:7,78:2,189,78,-1:13,189:3,142,189:2,-1:2,189:3,78,189:2,78,189:" +
"2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,143,189:5,-1:2,189:3,78,189:2," +
"78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189" +
":2,78,189:2,78,189,145,189,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189" +
":3,78,189:2,78,189:2,78,189:2,147,78:2,189:6,-1:7,78:2,189,78,-1:13,189:3,3" +
"9,189:2,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-" +
"1:13,189:5,40,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,18" +
"9,78,-1:13,189:4,41,189,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1" +
":7,78:2,189,78,-1:13,189:5,42,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,18" +
"9:6,-1:7,78:2,189,78,-1:13,189:4,43,189,-1:2,189:3,78,189:2,78,189:2,78,189" +
":3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,172,189:2,78,189:2,78,189:2" +
",78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:3,44,189:2,-1:2,189:3,78,18" +
"9:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:4,45,189,-1:2,1" +
"89:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:6,85,-1:6,18" +
"9:6,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13" +
",189,148,189:4,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,1" +
"89,78,-1:13,189:6,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189,46,189:4,-" +
"1:7,78:2,189,78,-1:13,189:6,-1:2,47,189:2,78,189:2,78,189:2,78,189:3,78:2,1" +
"89:6,-1:7,78:2,189,78,-1:13,189:5,48,-1:2,189:3,78,189:2,78,189:2,78,189:3," +
"78:2,189:6,-1:7,78:2,189,78,-1:13,189:3,149,189:2,-1:2,189:3,78,189:2,78,18" +
"9:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189,173," +
"78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189" +
":2,78,189:2,78,189:3,78:2,49,189:5,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3," +
"78,189:2,78,189:2,78,189:2,151,78:2,189:6,-1:7,78:2,189,78,-1:13,189,152,18" +
"9:4,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13" +
",189:5,154,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,7" +
"8,-1:13,189:5,51,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2" +
",189,78,-1:13,189:6,-1:2,189:3,78,155,189,78,189:2,78,189:3,78:2,189:6,-1:7" +
",78:2,189,78,-1:13,189:6,-1:2,189:3,78,189:2,78,189:2,78,189:2,156,78:2,189" +
":6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189,52,189,78,189:2,78,189:2,78,189:3," +
"78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189:2,78,189:2,78,189" +
":2,54,78:2,189:6,-1:7,78:2,189,78,-1:13,189:5,55,-1:2,189:3,78,189:2,78,189" +
":2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,82,189:2,78,189:2," +
"78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:3,111,189:2,-1:2,18" +
"9:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:5,184," +
"-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189" +
":6,-1:2,189,177,189,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78," +
"-1:13,189:6,-1:2,189:3,78,189:2,78,167,189,78,189:3,78:2,189:6,-1:7,78:2,18" +
"9,78,-1:13,189:6,-1:2,125,189:2,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7," +
"78:2,189,78,-1:13,189,119,189:4,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2," +
"189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189:2,78,189:2,78,189:2,12" +
"2,78:2,189:6,-1:7,78:2,189,78,-1:13,189:2,123,189:3,-1:2,189:3,78,189:2,78," +
"189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:4,132,189,-1:2,189:3,7" +
"8,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:" +
"3,78,189:2,78,189,180,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:5,137," +
"-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189" +
":6,-1:2,189:3,78,189:2,78,189:2,78,189:2,135,78:2,189:6,-1:7,78:2,189,78,-1" +
":13,189:6,-1:2,189:3,78,189,141,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189," +
"78,-1:13,189:3,146,189:2,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-" +
"1:7,78:2,189,78,-1:13,189:3,150,189:2,-1:2,189:3,78,189:2,78,189:2,78,189:3" +
",78:2,189:6,-1:7,78:2,189,78,-1:13,189,153,189:4,-1:2,189:3,78,189:2,78,189" +
":2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189,84,189,78,189:" +
"2,78,189:2,78,189:3,78:2,189,86,189:4,-1:7,78:2,189,78,-1:13,189:6,-1:2,189" +
",121,189,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6" +
",-1:2,189:3,78,189:2,78,120,189,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13," +
"189:6,-1:2,126,189:2,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78" +
",-1:13,189,169,189:4,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7," +
"78:2,189,78,-1:13,189:4,133,189,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2," +
"189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,189,144,78,189:2,78,189:3," +
"78:2,189:6,-1:7,78:2,189,78,-1:13,189:3,88,189,158,-1:2,189:3,78,189:2,78,1" +
"89:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189,166,189,78,1" +
"89:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,7" +
"8,189:2,78,124,189,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:4,136,189" +
",-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,18" +
"9:6,-1:2,189:3,78,189,90,78,189:2,78,189:3,78:2,189:4,92,189,-1:7,78:2,189," +
"78,-1:13,189:6,-1:2,189,168,189,78,189:2,78,189:2,78,189:3,78:2,189:6,-1:7," +
"78:2,189,78,-1:13,189:6,-1:2,189,160,189,78,189:2,78,189:2,78,189:2,94,78:2" +
",189:6,-1:7,78:2,189,78,-1:13,189:5,96,-1:2,98,189:2,78,189:2,78,189:2,78,1" +
"89:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78,100,189,78,189:2" +
",78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:5,101,-1:2,102,189:2,78,189" +
":2,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:3,78," +
"161,189,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1:2,189:" +
"3,78,189:2,78,189:2,78,103,189:2,78:2,189:6,-1:7,78:2,189,78,-1:13,189:6,-1" +
":2,189,163,189,78,189,176,78,189:2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:" +
"13,189:6,-1:2,189:3,78,189:2,78,189:2,78,189:2,104,78:2,189:6,-1:7,78:2,189" +
",78,-1:13,189:3,175,189:2,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2,189:6," +
"-1:7,78:2,189,78,-1:13,189:5,105,-1:2,189:3,78,189:2,78,189:2,78,189:3,78:2" +
",189:6,-1:7,78:2,189,78,-1:13,189,182,189:4,-1:2,106,189:2,78,189:2,78,189:" +
"2,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1:13,189,164,189:4,-1:2,189:3,78,18" +
"9:2,78,107,189,78,189:3,78:2,189:6,-1:7,78:2,189,78,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {
				return null;
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return new Symbol(sym._SYMB_0); }
					case -3:
						break;
					case 3:
						{ return new Symbol(sym._SYMB_1); }
					case -4:
						break;
					case 4:
						{ return new Symbol(sym._SYMB_2); }
					case -5:
						break;
					case 5:
						{ return new Symbol(sym._SYMB_3); }
					case -6:
						break;
					case 6:
						{ return new Symbol(sym._SYMB_10); }
					case -7:
						break;
					case 7:
						{ return new Symbol(sym._SYMB_5); }
					case -8:
						break;
					case 8:
						{ return new Symbol(sym._SYMB_6); }
					case -9:
						break;
					case 9:
						{ return new Symbol(sym._SYMB_7); }
					case -10:
						break;
					case 10:
						{ return new Symbol(sym._SYMB_8); }
					case -11:
						break;
					case 11:
						{ return new Symbol(sym._SYMB_9); }
					case -12:
						break;
					case 12:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -13:
						break;
					case 13:
						{ return new Symbol(sym._SYMB_12); }
					case -14:
						break;
					case 14:
						{ return new Symbol(sym._SYMB_13); }
					case -15:
						break;
					case 15:
						{ /* ignore white space. */ }
					case -16:
						break;
					case 16:
						{ yybegin(STRING); }
					case -17:
						break;
					case 17:
						{ return new Symbol(sym._INTEGER_, new Integer(yytext())); }
					case -18:
						break;
					case 18:
						{ return new Symbol(sym._SYMB_4); }
					case -19:
						break;
					case 19:
						{ return new Symbol(sym._SYMB_30); }
					case -20:
						break;
					case 20:
						{ return new Symbol(sym._SYMB_37); }
					case -21:
						break;
					case 21:
						{ yybegin(COMMENT); }
					case -22:
						break;
					case 22:
						{ return new Symbol(sym._SYMB_24); }
					case -23:
						break;
					case 23:
						{ return new Symbol(sym._SYMB_46); }
					case -24:
						break;
					case 24:
						{ return new Symbol(sym._SYMB_20); }
					case -25:
						break;
					case 25:
						{ return new Symbol(sym._SYMB_18); }
					case -26:
						break;
					case 26:
						{ return new Symbol(sym._SYMB_29); }
					case -27:
						break;
					case 27:
						{ return new Symbol(sym._SYMB_36); }
					case -28:
						break;
					case 28:
						{ /* BNFC single-line comment */ }
					case -29:
						break;
					case 29:
						{ return new Symbol(sym._DOUBLE_, new Double(yytext())); }
					case -30:
						break;
					case 30:
						{ return new Symbol(sym._SYMB_23); }
					case -31:
						break;
					case 31:
						{ return new Symbol(sym._SYMB_45); }
					case -32:
						break;
					case 32:
						{ return new Symbol(sym._SYMB_44); }
					case -33:
						break;
					case 33:
						{ return new Symbol(sym._SYMB_42); }
					case -34:
						break;
					case 34:
						{ return new Symbol(sym._SYMB_25); }
					case -35:
						break;
					case 35:
						{ return new Symbol(sym._SYMB_15); }
					case -36:
						break;
					case 36:
						{ return new Symbol(sym._SYMB_38); }
					case -37:
						break;
					case 37:
						{ return new Symbol(sym._SYMB_21); }
					case -38:
						break;
					case 38:
						{ return new Symbol(sym._SYMB_40); }
					case -39:
						break;
					case 39:
						{ return new Symbol(sym._SYMB_28); }
					case -40:
						break;
					case 40:
						{ return new Symbol(sym._SYMB_27); }
					case -41:
						break;
					case 41:
						{ return new Symbol(sym._SYMB_35); }
					case -42:
						break;
					case 42:
						{ return new Symbol(sym._SYMB_22); }
					case -43:
						break;
					case 43:
						{ return new Symbol(sym._SYMB_32); }
					case -44:
						break;
					case 44:
						{ return new Symbol(sym._SYMB_43); }
					case -45:
						break;
					case 45:
						{ return new Symbol(sym._SYMB_26); }
					case -46:
						break;
					case 46:
						{ return new Symbol(sym._SYMB_34); }
					case -47:
						break;
					case 47:
						{ return new Symbol(sym._SYMB_33); }
					case -48:
						break;
					case 48:
						{ return new Symbol(sym._SYMB_16); }
					case -49:
						break;
					case 49:
						{ return new Symbol(sym._SYMB_19); }
					case -50:
						break;
					case 50:
						{ return new Symbol(sym._SYMB_11); }
					case -51:
						break;
					case 51:
						{ return new Symbol(sym._SYMB_41); }
					case -52:
						break;
					case 52:
						{ return new Symbol(sym._SYMB_31); }
					case -53:
						break;
					case 53:
						{ return new Symbol(sym._SYMB_14); }
					case -54:
						break;
					case 54:
						{ return new Symbol(sym._SYMB_17); }
					case -55:
						break;
					case 55:
						{ return new Symbol(sym._SYMB_39); }
					case -56:
						break;
					case 56:
						{ }
					case -57:
						break;
					case 57:
						{ }
					case -58:
						break;
					case 58:
						{ yybegin(YYINITIAL); }
					case -59:
						break;
					case 59:
						{ pstring += yytext(); }
					case -60:
						break;
					case 60:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return new Symbol(sym._STRING_, foo.intern()); }
					case -61:
						break;
					case 61:
						{ yybegin(ESCAPED); }
					case -62:
						break;
					case 62:
						{ pstring += yytext(); yybegin(STRING); }
					case -63:
						break;
					case 63:
						{ pstring += "\t"; yybegin(STRING); }
					case -64:
						break;
					case 64:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -65:
						break;
					case 65:
						{ pstring += "\""; yybegin(STRING); }
					case -66:
						break;
					case 66:
						{ pstring += "\\"; yybegin(STRING); }
					case -67:
						break;
					case 68:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -68:
						break;
					case 69:
						{ return new Symbol(sym._DOUBLE_, new Double(yytext())); }
					case -69:
						break;
					case 70:
						{ }
					case -70:
						break;
					case 72:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -71:
						break;
					case 74:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -72:
						break;
					case 76:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -73:
						break;
					case 78:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -74:
						break;
					case 80:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -75:
						break;
					case 82:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -76:
						break;
					case 84:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -77:
						break;
					case 86:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -78:
						break;
					case 88:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -79:
						break;
					case 90:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -80:
						break;
					case 92:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -81:
						break;
					case 94:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -82:
						break;
					case 96:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -83:
						break;
					case 98:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -84:
						break;
					case 100:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -85:
						break;
					case 101:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -86:
						break;
					case 102:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -87:
						break;
					case 103:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -88:
						break;
					case 104:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -89:
						break;
					case 105:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -90:
						break;
					case 106:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -91:
						break;
					case 107:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -92:
						break;
					case 108:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -93:
						break;
					case 109:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -94:
						break;
					case 110:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -95:
						break;
					case 111:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -96:
						break;
					case 112:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -97:
						break;
					case 113:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -98:
						break;
					case 114:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -99:
						break;
					case 115:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -100:
						break;
					case 116:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -101:
						break;
					case 117:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -102:
						break;
					case 118:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -103:
						break;
					case 119:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -104:
						break;
					case 120:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -105:
						break;
					case 121:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -106:
						break;
					case 122:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -107:
						break;
					case 123:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -108:
						break;
					case 124:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -109:
						break;
					case 125:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -110:
						break;
					case 126:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -111:
						break;
					case 127:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -112:
						break;
					case 128:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -113:
						break;
					case 129:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -114:
						break;
					case 130:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -115:
						break;
					case 131:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -116:
						break;
					case 132:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -117:
						break;
					case 133:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -118:
						break;
					case 134:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -119:
						break;
					case 135:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -120:
						break;
					case 136:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -121:
						break;
					case 137:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -122:
						break;
					case 138:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -123:
						break;
					case 139:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -124:
						break;
					case 140:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -125:
						break;
					case 141:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -126:
						break;
					case 142:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -127:
						break;
					case 143:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -128:
						break;
					case 144:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -129:
						break;
					case 145:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -130:
						break;
					case 146:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -131:
						break;
					case 147:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -132:
						break;
					case 148:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -133:
						break;
					case 149:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -134:
						break;
					case 150:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -135:
						break;
					case 151:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -136:
						break;
					case 152:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -137:
						break;
					case 153:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -138:
						break;
					case 154:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -139:
						break;
					case 155:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -140:
						break;
					case 156:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -141:
						break;
					case 157:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -142:
						break;
					case 158:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -143:
						break;
					case 159:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -144:
						break;
					case 160:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -145:
						break;
					case 161:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -146:
						break;
					case 162:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -147:
						break;
					case 163:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -148:
						break;
					case 164:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -149:
						break;
					case 165:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -150:
						break;
					case 166:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -151:
						break;
					case 167:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -152:
						break;
					case 168:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -153:
						break;
					case 169:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -154:
						break;
					case 170:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -155:
						break;
					case 171:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -156:
						break;
					case 172:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -157:
						break;
					case 173:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -158:
						break;
					case 174:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -159:
						break;
					case 175:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -160:
						break;
					case 176:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -161:
						break;
					case 177:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -162:
						break;
					case 178:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -163:
						break;
					case 179:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -164:
						break;
					case 180:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -165:
						break;
					case 181:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -166:
						break;
					case 182:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -167:
						break;
					case 183:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -168:
						break;
					case 184:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -169:
						break;
					case 185:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -170:
						break;
					case 186:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -171:
						break;
					case 187:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -172:
						break;
					case 188:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -173:
						break;
					case 189:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -174:
						break;
					case 190:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -175:
						break;
					case 191:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -176:
						break;
					case 192:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -177:
						break;
					case 193:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -178:
						break;
					case 194:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -179:
						break;
					case 195:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -180:
						break;
					case 196:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -181:
						break;
					case 197:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -182:
						break;
					case 198:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -183:
						break;
					case 199:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -184:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
