package fafl.Absyn; // Java Package generated by the BNF Converter.

public abstract class AFuncReturnType implements java.io.Serializable {
  public abstract <R,A> R accept(AFuncReturnType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(fafl.Absyn.FuncReturnType p, A arg);

  }

}
