package fafl.Absyn; // Java Package generated by the BNF Converter.

public abstract class Args implements java.io.Serializable {
  public abstract <R,A> R accept(Args.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(fafl.Absyn.Arguments p, A arg);

  }

}
