package fafl.Absyn; // Java Package generated by the BNF Converter.

public class Arguments extends Args {
  public final ListArg listarg_;
  public Arguments(ListArg p1) { listarg_ = p1; }

  public <R,A> R accept(fafl.Absyn.Args.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.Arguments) {
      fafl.Absyn.Arguments x = (fafl.Absyn.Arguments)o;
      return this.listarg_.equals(x.listarg_);
    }
    return false;
  }

  public int hashCode() {
    return this.listarg_.hashCode();
  }


}
