package fafl.Absyn; // Java Package generated by the BNF Converter.

public class ArrayConstructor extends Expr {
  public final Type type_;
  public final Expr expr_;
  public final ListExpr listexpr_;
  public ArrayConstructor(Type p1, Expr p2, ListExpr p3) { type_ = p1; expr_ = p2; listexpr_ = p3; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.ArrayConstructor) {
      fafl.Absyn.ArrayConstructor x = (fafl.Absyn.ArrayConstructor)o;
      return this.type_.equals(x.type_) && this.expr_.equals(x.expr_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.type_.hashCode())+this.expr_.hashCode())+this.listexpr_.hashCode();
  }


}
