package fafl.Absyn; // Java Package generated by the BNF Converter.

public abstract class AStructField implements java.io.Serializable {
  public abstract <R,A> R accept(AStructField.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(fafl.Absyn.StructField p, A arg);

  }

}
