package fafl.Absyn; // Java Package generated by the BNF Converter.

public abstract class ATypedArg implements java.io.Serializable {
  public abstract <R,A> R accept(ATypedArg.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(fafl.Absyn.TypedArg p, A arg);

  }

}
