package fafl.Absyn; // Java Package generated by the BNF Converter.

public abstract class Bool implements java.io.Serializable {
  public abstract <R,A> R accept(Bool.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(fafl.Absyn.BoolTrue p, A arg);
    public R visit(fafl.Absyn.BoolFalse p, A arg);

  }

}
