package fafl.Absyn; // Java Package generated by the BNF Converter.

public class BoolConst extends Expr {
  public final Bool bool_;
  public BoolConst(Bool p1) { bool_ = p1; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.BoolConst) {
      fafl.Absyn.BoolConst x = (fafl.Absyn.BoolConst)o;
      return this.bool_.equals(x.bool_);
    }
    return false;
  }

  public int hashCode() {
    return this.bool_.hashCode();
  }


}
