package fafl.Absyn; // Java Package generated by the BNF Converter.

public class Define extends Expr {
  public final String ident_;
  public final ListATypedArg listatypedarg_;
  public final AFuncReturnType afuncreturntype_;
  public final Expr expr_;
  public Define(String p1, ListATypedArg p2, AFuncReturnType p3, Expr p4) { ident_ = p1; listatypedarg_ = p2; afuncreturntype_ = p3; expr_ = p4; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.Define) {
      fafl.Absyn.Define x = (fafl.Absyn.Define)o;
      return this.ident_.equals(x.ident_) && this.listatypedarg_.equals(x.listatypedarg_) && this.afuncreturntype_.equals(x.afuncreturntype_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.ident_.hashCode())+this.listatypedarg_.hashCode())+this.afuncreturntype_.hashCode())+this.expr_.hashCode();
  }


}
