package fafl.Absyn; // Java Package generated by the BNF Converter.

public class DictSet extends Expr {
  public final Expr expr_;
  public final Pair pair_;
  public DictSet(Expr p1, Pair p2) { expr_ = p1; pair_ = p2; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.DictSet) {
      fafl.Absyn.DictSet x = (fafl.Absyn.DictSet)o;
      return this.expr_.equals(x.expr_) && this.pair_.equals(x.pair_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.pair_.hashCode();
  }


}
