package fafl.Absyn; // Java Package generated by the BNF Converter.

public class DictConstructor extends Expr {
  public final String ident_;
  public final Type type_1, type_2;
  public final ListPair listpair_;
  public DictConstructor(String p1, Type p2, Type p3, ListPair p4) { ident_ = p1; type_1 = p2; type_2 = p3; listpair_ = p4; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.DictConstructor) {
      fafl.Absyn.DictConstructor x = (fafl.Absyn.DictConstructor)o;
      return this.ident_.equals(x.ident_) && this.type_1.equals(x.type_1) && this.type_2.equals(x.type_2) && this.listpair_.equals(x.listpair_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.ident_.hashCode())+this.type_1.hashCode())+this.type_2.hashCode())+this.listpair_.hashCode();
  }


}
