package fafl.Absyn; // Java Package generated by the BNF Converter.

public class DictPair extends Pair {
  public final Expr expr_1, expr_2;
  public DictPair(Expr p1, Expr p2) { expr_1 = p1; expr_2 = p2; }

  public <R,A> R accept(fafl.Absyn.Pair.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.DictPair) {
      fafl.Absyn.DictPair x = (fafl.Absyn.DictPair)o;
      return this.expr_1.equals(x.expr_1) && this.expr_2.equals(x.expr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_1.hashCode())+this.expr_2.hashCode();
  }


}
