package fafl.Absyn; // Java Package generated by the BNF Converter.

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(fafl.Absyn.SetqSimple p, A arg);
    public R visit(fafl.Absyn.SetqStruct p, A arg);
    public R visit(fafl.Absyn.IntConst p, A arg);
    public R visit(fafl.Absyn.DoubleConst p, A arg);
    public R visit(fafl.Absyn.BoolConst p, A arg);
    public R visit(fafl.Absyn.StringConst p, A arg);
    public R visit(fafl.Absyn.Id p, A arg);
    public R visit(fafl.Absyn.FuncCall p, A arg);
    public R visit(fafl.Absyn.Define p, A arg);
    public R visit(fafl.Absyn.DefineWithExc p, A arg);
    public R visit(fafl.Absyn.StructInit p, A arg);
    public R visit(fafl.Absyn.StructConstructor p, A arg);
    public R visit(fafl.Absyn.StructField p, A arg);
    public R visit(fafl.Absyn.If p, A arg);
    public R visit(fafl.Absyn.Lambda p, A arg);
    public R visit(fafl.Absyn.DictConstructor p, A arg);
    public R visit(fafl.Absyn.DictSet p, A arg);
    public R visit(fafl.Absyn.DictGet p, A arg);
    public R visit(fafl.Absyn.DictRemove p, A arg);
    public R visit(fafl.Absyn.DictKeys p, A arg);
    public R visit(fafl.Absyn.DictValues p, A arg);
    public R visit(fafl.Absyn.DictLength p, A arg);
    public R visit(fafl.Absyn.ArrayConstructor p, A arg);
    public R visit(fafl.Absyn.First p, A arg);
    public R visit(fafl.Absyn.Last p, A arg);
    public R visit(fafl.Absyn.ArrayGet p, A arg);
    public R visit(fafl.Absyn.ArraySet p, A arg);
    public R visit(fafl.Absyn.ArrayLength p, A arg);
    public R visit(fafl.Absyn.TupleConstructor p, A arg);
    public R visit(fafl.Absyn.TupleGet p, A arg);
    public R visit(fafl.Absyn.TupleLength p, A arg);
    public R visit(fafl.Absyn.RaiseEx p, A arg);
    public R visit(fafl.Absyn.TryCatch p, A arg);
    public R visit(fafl.Absyn.Plus p, A arg);
    public R visit(fafl.Absyn.Minus p, A arg);
    public R visit(fafl.Absyn.Mul p, A arg);
    public R visit(fafl.Absyn.Div p, A arg);
    public R visit(fafl.Absyn.ToDouble p, A arg);
    public R visit(fafl.Absyn.ToInt p, A arg);
    public R visit(fafl.Absyn.ToString p, A arg);
    public R visit(fafl.Absyn.Equals p, A arg);
    public R visit(fafl.Absyn.IsLess p, A arg);
    public R visit(fafl.Absyn.IsGreater p, A arg);
    public R visit(fafl.Absyn.And p, A arg);
    public R visit(fafl.Absyn.Or p, A arg);
    public R visit(fafl.Absyn.ReadLine p, A arg);
    public R visit(fafl.Absyn.PrintLine p, A arg);

  }

}
