package fafl.Absyn; // Java Package generated by the BNF Converter.

public class FuncReturnType extends AFuncReturnType {
  public final Type type_;
  public FuncReturnType(Type p1) { type_ = p1; }

  public <R,A> R accept(fafl.Absyn.AFuncReturnType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.FuncReturnType) {
      fafl.Absyn.FuncReturnType x = (fafl.Absyn.FuncReturnType)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
