package fafl.Absyn; // Java Package generated by the BNF Converter.

public class Lambda extends Expr {
  public final ListATypedArg listatypedarg_;
  public final AFuncReturnType afuncreturntype_;
  public final Expr expr_;
  public Lambda(ListATypedArg p1, AFuncReturnType p2, Expr p3) { listatypedarg_ = p1; afuncreturntype_ = p2; expr_ = p3; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.Lambda) {
      fafl.Absyn.Lambda x = (fafl.Absyn.Lambda)o;
      return this.listatypedarg_.equals(x.listatypedarg_) && this.afuncreturntype_.equals(x.afuncreturntype_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.listatypedarg_.hashCode())+this.afuncreturntype_.hashCode())+this.expr_.hashCode();
  }


}
