package fafl.Absyn; // Java Package generated by the BNF Converter.

public abstract class Pair implements java.io.Serializable {
  public abstract <R,A> R accept(Pair.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(fafl.Absyn.DictPair p, A arg);

  }

}
