package fafl.Absyn; // Java Package generated by the BNF Converter.

public class RaiseEx extends Raise {
  public final String string_;
  public RaiseEx(String p1) { string_ = p1; }

  public <R,A> R accept(fafl.Absyn.Raise.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.RaiseEx) {
      fafl.Absyn.RaiseEx x = (fafl.Absyn.RaiseEx)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
