package fafl.Absyn; // Java Package generated by the BNF Converter.

public class ReadLine extends Expr {
  public ReadLine() { }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.ReadLine) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
