package fafl.Absyn; // Java Package generated by the BNF Converter.

public class Set extends Expr {
  public final String ident_;
  public final Pair pair_;
  public Set(String p1, Pair p2) { ident_ = p1; pair_ = p2; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.Set) {
      fafl.Absyn.Set x = (fafl.Absyn.Set)o;
      return this.ident_.equals(x.ident_) && this.pair_.equals(x.pair_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.pair_.hashCode();
  }


}
