package fafl.Absyn; // Java Package generated by the BNF Converter.

public class SetqStruct extends Expr {
  public final String ident_1, ident_2;
  public final Args args_;
  public SetqStruct(String p1, String p2, Args p3) { ident_1 = p1; ident_2 = p2; args_ = p3; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.SetqStruct) {
      fafl.Absyn.SetqStruct x = (fafl.Absyn.SetqStruct)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2) && this.args_.equals(x.args_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_1.hashCode())+this.ident_2.hashCode())+this.args_.hashCode();
  }


}
