package fafl.Absyn; // Java Package generated by the BNF Converter.

public class StructField extends Expr {
  public final String ident_1, ident_2;
  public StructField(String p1, String p2) { ident_1 = p1; ident_2 = p2; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.StructField) {
      fafl.Absyn.StructField x = (fafl.Absyn.StructField)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_1.hashCode())+this.ident_2.hashCode();
  }


}
