package fafl.Absyn; // Java Package generated by the BNF Converter.

public class StructField extends Expr {
  public final Expr expr_;
  public final String ident_;
  public StructField(Expr p1, String p2) { expr_ = p1; ident_ = p2; }

  public <R,A> R accept(fafl.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof fafl.Absyn.StructField) {
      fafl.Absyn.StructField x = (fafl.Absyn.StructField)o;
      return this.expr_.equals(x.expr_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.ident_.hashCode();
  }


}
