package com.Absyn; // Java Package generated by the BNF Converter.

public class Minus extends Expr {
  public final ListParams listparams_;
  public Minus(ListParams p1) { listparams_ = p1; }

  public <R,A> R accept(com.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.Absyn.Minus) {
      com.Absyn.Minus x = (com.Absyn.Minus)o;
      return this.listparams_.equals(x.listparams_);
    }
    return false;
  }

  public int hashCode() {
    return this.listparams_.hashCode();
  }


}
