package com.Absyn; // Java Package generated by the BNF Converter.

public abstract class Params implements java.io.Serializable {
  public abstract <R,A> R accept(Params.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.Absyn.ParametersInteger p, A arg);
    public R visit(com.Absyn.ParametersFunctions p, A arg);
    public R visit(com.Absyn.ParametersIdents p, A arg);

  }

}
