package com.Absyn; // Java Package generated by the BNF Converter.

public class ParametersInteger extends Params {
  public final Integer integer_;
  public ParametersInteger(Integer p1) { integer_ = p1; }

  public <R,A> R accept(com.Absyn.Params.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.Absyn.ParametersInteger) {
      com.Absyn.ParametersInteger x = (com.Absyn.ParametersInteger)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
