package com.Absyn; // Java Package generated by the BNF Converter.

public class ParametersIdents extends Params {
  public final String ident_;
  public ParametersIdents(String p1) { ident_ = p1; }

  public <R,A> R accept(com.Absyn.Params.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.Absyn.ParametersIdents) {
      com.Absyn.ParametersIdents x = (com.Absyn.ParametersIdents)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
