package com.Absyn; // Java Package generated by the BNF Converter.

public class Plus extends Expr {
  public final ListParams listparams_;
  public Plus(ListParams p1) { listparams_ = p1; }

  public <R,A> R accept(com.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.Absyn.Plus) {
      com.Absyn.Plus x = (com.Absyn.Plus)o;
      return this.listparams_.equals(x.listparams_);
    }
    return false;
  }

  public int hashCode() {
    return this.listparams_.hashCode();
  }


}
