package com.Absyn; // Java Package generated by the BNF Converter.

public class Program extends ProgramExprs {
  public final ListExpr listexpr_;
  public Program(ListExpr p1) { listexpr_ = p1; }

  public <R,A> R accept(com.Absyn.ProgramExprs.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.Absyn.Program) {
      com.Absyn.Program x = (com.Absyn.Program)o;
      return this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexpr_.hashCode();
  }


}
